FROM python:2.7

ENV SHELL=/bin/bash
RUN apt-get update -y && apt-get upgrade -y

RUN mkdir -p /srv/
RUN chmod -R 777 /srv/
RUN mkdir -p /srv/datasets
RUN wget -q https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2016-01.csv -O /srv/datasets/yellow_tripdata_2016-01.csv

RUN mkdir -p /srv/src/
RUN mkdir -p /srv/parquet/
RUN mkdir -p /srv/parquet/incoming

COPY misc/parqueryd.cfg /etc/parqueryd.cfg

COPY . /srv/src/parqueryd/
WORKDIR /srv/src/parqueryd/
RUN pip install -e .[test]

# Keep the container running
CMD sleep infinity

