FROM python:2.7

ENV SHELL=/bin/bash

ARG PIP_INDEX_URL

RUN apt-get update -y && apt-get upgrade -y

RUN mkdir -p /srv/ && mkdir -p /srv/datasets && mkdir -p /srv/src/ && mkdir -p /srv/parquet/ && mkdir -p /srv/parquet/incoming && chmod -R 777 /srv/ 
RUN apt-get install -y wget

# CSV file not available online anymore. Add to the repository folder
ADD test_data/yellow_tripdata_2016-01.csv /srv/datasets/yellow_tripdata_2016-01.csv

COPY misc/parqueryd.cfg /etc/parqueryd.cfg

COPY . /srv/src/parqueryd/
WORKDIR /srv/src/parqueryd/

RUN pip install awscli
RUN aws codeartifact login --tool pip --repository private --domain visualfabriq --domain-owner 103613169272 --region eu-west-1
RUN pip install -e .[test]

# Keep the container running
CMD sleep infinity

