FROM python:2.7

ENV SHELL=/bin/bash
RUN apt-get update -y && apt-get upgrade -y
COPY misc/parqueryd.cfg /etc/parqueryd.cfg

RUN mkdir -p /srv/ && mkdir -p /srv/datasets && mkdir -p /srv/src/ && mkdir -p /srv/parquet/

RUN wget -q https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2016-01.csv -O /srv/datasets/yellow_tripdata_2016-01.csv

COPY . /srv/src/parqueryd/
WORKDIR /srv/src/parqueryd/
RUN pip install numpy==1.16.5 azure-storage-blob==12.0.0
RUN pip install -e .[test]
# Keep the container running
CMD sleep infinity

