version: "3.4"
services:
  redis:
    image: redis
    networks:
      default:
        aliases:
          - redis

  localstack:
    image: localstack/localstack
    ports:
      - "4567-4584:4567-4584"
    environment:
      - SERVICES=s3
      - HOSTNAME=localstack
      - DEFAULT_REGION=eu-west-1

  parqueryd:
    image: parqueryd
    build:
      network: host
      context: .
      dockerfile: DockerFile
    volumes:
      - test-results:/srv/src/parqueryd/test-results
    depends_on:
      - redis
      - localstack
